spring:
  application:
    name: premisave-messenger-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/premisave-messenger

  redis:
    host: localhost
    port: 6379

  websocket:
    stomp:
      broker:
        heartbeat: 10000

server:
  port: 8081

auth:
  service:
    url: http://localhost:8080

jwt:
  secret: eW91ci12ZXJ5LXNlY3VyZS1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcyE=

cloudinary:
  cloud-name: thepeacemakersllc
  api-key: 929659223288334
  api-secret: nAsBdgfXx86u7-Y8X2VnLa-2FbQ

logging:
  level:
    com.premisave.messenger: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.data.mongodb: INFO

profile-views:
  max-history-size: 20

rate-limit:
  requests-per-minute: 60